version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: group15_database
      MYSQL_USER: group15
      MYSQL_PASSWORD: group15password
      MYSQL_ROOT_PASSWORD: group15password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - common-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: group15password
    ports:
      - '8080:80'
    networks:
      - common-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME= admin
      - MONGO_INITDB_ROOT_PASSWORD= password
    volumes:
      - mongo-data:/data/db
    networks:
      - common-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME= admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD= password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

# Define named volumes
volumes:
  db_data:
  mongo-data:
